In [36]:
# 행렬 생성함수 numpy.array([]) / [] 1차원 배열(벡터)형식으로 생성, [],[] =>2차원(매트릭스)
import numpy as np
b = np.array([[1,2,3]])
print(b)
print(type(b))

[[1 2 3]]
<class 'numpy.ndarray'>


In [37]:
print(b.shape) #shape : 배열이 몇 차원인지 알아보는 함수 -> (행,열) 형식으로 나타나면 2차원 배열

(1, 3)


In [38]:
b[0,0]

1

In [39]:
#numpy.zeros((행,열)) : 모든 요소가 0인 행렬 생성
aa=np.zeros((2,2))
print(aa)
type(aa)

[[0. 0.]
 [0. 0.]]


numpy.ndarray

In [40]:
#numpy.ones((행,열)) : 모든 요소가 1인 행렬 생성
aa=np.ones((2,3))
print(aa)

[[1. 1. 1.]
 [1. 1. 1.]]


In [41]:
#numpy.full((행,열),값) : 원하는 값을 요소로 행렬 생성
aa=np.full((2,3),100)
print(aa)

[[100 100 100]
 [100 100 100]]


In [42]:
#numpy.eye(n차행렬) : 대각선이 1이고 나머지가 0인 n차 행렬 생성
aa=np.eye(6)
print(aa)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [43]:
#reshape((행,열)) : 배열된 요소를 입력한 행,열 값으로 재구성
aa=np.array(range(30)).reshape((3,10))
print(aa)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [44]:
#numpy 슬라이싱 -> 매트릭스[행 시작점:끝점, 열 시작점 : 끝점]
#시작점부터 끝점 앞까지 잘라 원하는 만큼의 행렬 생성 가능

list = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

arr = np.array(list)

a = arr[0:2,0:2]

print(a)

[[1 2]
 [4 5]]


In [45]:
a2 = arr[1:,1:]
print(a2)

[[5 6]
 [8 9]]


In [46]:
#numpy 정수 인덱싱(integer indexing)

#numpy 배열 a에 대해서 a[[row1,row2],[col1,col2]]는
#a[row1,col1]와 a[row2,col2]라는 2개의 배열 요소 집합을 의미

list2 = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

a3 = np.array(list2)

#정수 인덱싱
res = a3[[0,2],[1,3]] # a3[[행],[열]] => a3[0,1],a3[2,3]
print(res)

[ 2 12]


In [47]:
type(res)

numpy.ndarray

In [48]:
#부울린 인덱싱 (boolean indexing)
list3 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

a4 = np.array(list3)

b_a4 = np.array([
    [False,True,False],
    [True,False,True],
    [False,True,False]
])
n = a4[b_a4]

print(n)


[2 4 6 8]


In [49]:
#부울린 인덱싱 배열을 생성할 때 표현식으로 이용하기

#배열 a에 대해서 짝수인 배열 요소만 True로 지정하겠다 하면
#b_arr=(a%2==0)

list5 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

arr = np.array(list5)

#배열 arr에 대해 짝수면 True, 홀수면 False
b_arr=(arr%2==0)
print(b_arr)

[[False  True False]
 [ True False  True]
 [False  True False]]


In [50]:
print(arr[b_arr])

[2 4 6 8]


In [51]:
n=arr[arr%2==0]
print(n)

[2 4 6 8]


In [52]:
#numpy 연산

#연산자를 이용할 경우에는 +,-,*,/
#함수를 사용할 경우에는 add(),substract(),multiply(),divide()
#배열 a와 배열 b가 있을 때, a+b는 a[0] + b[0], a[1]+b[1]... 와 같은 방식으로 결과를 리턴

a=np.array([1,2,3])
b = np.array([4,5,6])

c = a + b
print(c)

c2= np.add(a,b)
print(c2)

[5 7 9]
[5 7 9]


In [53]:
d = a-b
print(d)
d2 = np.subtract(a,b)
print(d2)

[-3 -3 -3]
[-3 -3 -3]


In [54]:
e = a*b
print(e)
e2 = np.multiply(a,b)
print(e2)

[ 4 10 18]
[ 4 10 18]


In [55]:
f = a/b
print(f)
f2 = np.divide(a,b)
print(f2)

[0.25 0.4  0.5 ]
[0.25 0.4  0.5 ]


In [56]:
#matrix product function -> dot()

m1 = [
    [1,2],
    [3,4]
]
m2 = [
    [2,4],
    [6,8]
]

arr_m1 = np.array(m1)
arr_m2 = np.array(m2)

#numpy에서 vector와 matrix의 product를 구하기 위해서는 dot()함수를 이용한다.

pr_m = np.dot(m1,m2)
print(pr_m)

[[14 20]
 [30 44]]


In [57]:
#numpy에서는 배열간의 연산을 위한 여러 함수들을 제공하는데,
#각 배열의 요소를 더하는 함수 -> sum()
#각 배열의 요소를 곱하는 함수 -> prod()
#이 함수들은 axis 옵션을 사용한다. axis = 0 -> col끼리 더함 / axis = 1 -> row끼리 더함

a = np.array([[1,2],[3,4]])
s = np.sum(a)

print(s)

10


In [58]:
s2 = np.sum(a,axis=0)
print(s2)

[4 6]


In [59]:
s3 = np.sum(a,axis=1)
print(s3)

[3 7]


In [60]:
p = np.prod(a)
print(p)

24


In [61]:
p2 = np.prod(a,axis = 0)
print(p2)

[3 8]


In [62]:
p3=np.prod(a,axis=1)
print(p3)

[ 2 12]


In [63]:
#numpy 자료형 (data type)

#int, float, bool(T/F)

# 정수형(int:integer)
# -int8, int16, int32, int64 (부호가 있는 정수형)
# uint(Unsigned integer) : unit8(0~255), unit16(0~65535),unit32, unit 64

#실수형(float)
#float16, float32, float61

#complex
#complex64 : 두개의 32비트 부동 소수점으로 표시되는 복소수
#complex128 : 두개의 64비트 부동 소수점으로 표시되는 복소수

#데이터의 type을 알아보기 위한 dtype

X = np.float32(1.0)

print(X)
print(type(X))

1.0
<class 'numpy.float32'>


In [64]:
print(X.dtype)

float32


In [65]:
z = np.arange(5) #arange(값) : 0~값-1 만큼 순서대로 나열
print(z)

[0 1 2 3 4]


In [66]:
zf = np.arange(5,dtype='f')
print(zf)

[0. 1. 2. 3. 4.]


In [67]:
zf2 = np.array([1,2,3],dtype='f')
print(zf2,zf2.dtype)

[1. 2. 3.] float32


In [68]:
zi2 = np.int8(zf2)
print(zi2,zi2.dtype)

[1 2 3] int8


In [69]:
bb = np.arange(10)
print(bb)

[0 1 2 3 4 5 6 7 8 9]


In [70]:
cc=np.arange(3,10) #np.arange(시작점,끝점)
print(cc)

[3 4 5 6 7 8 9]


In [71]:
dd = np.arange(2,3)
print(dd)

[2]


In [72]:
dd2 = np.arange(2,3,0.1)
print(dd2)

[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [73]:
# numpy 브로드캐스트 : shape가 다른 것끼리 연산

a=np.array([[1,2],[3,4]])
b=10
c=a*b
print(c)

[[10 20]
 [30 40]]


In [74]:
x=np.array([[1,2],[3,4]])
y=np.array([[10,20]])
z=x*y
print(z)

[[10 40]
 [30 80]]


In [75]:
x=np.array([[11,21],[34,43],[0,9]])
print(x)

[[11 21]
 [34 43]
 [ 0  9]]


In [76]:
x[0,1]

21

In [77]:
for row in x :
    print(row)

[11 21]
[34 43]
[0 9]


In [78]:
#2차원 배열을 1차원 배열로 변환(평탄화) : flatten()

x = x.flatten()
print(x)

[11 21 34 43  0  9]


In [79]:
print(x[np.array([1,3,5])]) #1차원 배열에서 각 요소만 뽑고 싶을 때

[21 43  9]


In [80]:
print(x[x>25]) #x>25인 원소만 나타냄

print(x>25) #부울린 형식으로 출력, *넘파이 배열에 부호를 이용하면 bool배열로 나타남

[34 43]
[False False  True  True False False]
